version: "3.8"
name: "Video Palace Infrastructure"

services:
  videopalace_mongodb:
    image: mongo
    container_name: videopalace_mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
  videopalace_rabbitmq:
    image: rabbitmq:management
    container_name: videopalace_rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: videopalace_rabbitmq

volumes:
  mongodbdata:
  rabbitmqdata:
